import React,{useEffect,useState} from 'react'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
// import Dummy from '../Components/Dummy'
// import '../styles/style.css'   global css cannot be imported from files it can only be used in app.js
export default function Home() {
  const [blogs,setBlogs]=useState([])
    useEffect(()=>{
      console.log("I have used useEffect in the index page");
      //Now fetch the blogs api
      fetch("http://localhost:3000/api/blogs")
      .then(response => response.json())
          // 4. Setting *dogImage* to the image url that we received from the response above
      .then(data => setBlogs(data))
    },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>Hunting Coder</span>
        </h1>
      <div className={styles.imageWrap}>
        {/* <Image src="/huntingcoder.webp" width={462} height={280}></Image> */}
        <img src="/huntingcoder.webp" width={462} height={280} alt="" className={styles.image} />
      </div>
        <h2 className={styles.description}>
        Popular Blogs
        </h2>
        {blogs.map((blog)=>{
                return  <div className="blogs" key={blog.title}>
                <div className="blog">
                  <Link href={`/blogpost/${blog.slug}`}><a><h3>{blog.title}</h3></a></Link>
                  <p>{blog.metadesc.substr(0,100)}.......</p>
                </div>
              </div>
          })}
      
    </main>
      
    </div>
  )
}
